apiVersion: apps/v1
kind: Deployment
metadata:
  name: happybus-node-deployment
  labels:
    app: happybus-node
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: happybus-node
  template:
    metadata: 
      labels:
        app: happybus-node
    spec:
      containers:
      - name: happybus-node
        image: mgmtsv-registry.cloudzcp.io/template/happybus-node_img:1
        ports: 
        - containerPort: 3005
        imagePullPolicy: Always